files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      language:
        de: de
    translate_attributes: '0'
  - source: /app/src/main/play/en-US/*/*
    translation: /app/src/main/play/%locale_with_underscore%/listing/%original_file_name%
  - source: /app/src/main/play/en-US/*
    translation: /app/src/main/play/%locale_with_underscore%/%original_file_name%
